### ISSUE TITLE
[minor] [Update "master" to "main" ]

### ISSUE THREAD

**Issue by umar07** [Yatharth0045/CodeTalkers#8]
In [WELCOME.md](https://github.com/Yatharth0045/CodeTalkers/blob/main/WELCOME.md) , Steps to update already forked repository with updated upstream repo has used "master" while it should be "main" in the commands given in step-**2** and step-**3**.

Else, the following error occurs
```
fatal: couldn't find remote ref master
```

**Comment by Yatharth0045** [comment]
Thanks for the update @umar07

**Comment by Yatharth0045** [comment]
Now fixed @umar07
